package cn.ncu.edu.onlineshopmall.entity;

public class ImagePath {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagepath.pathId
     *
     * @mbg.generated Wed Jul 24 09:45:07 CST 2019
     */
    private int pathid;

    public void setPathid(int pathid) {
        this.pathid = pathid;
    }

    public ImagePath(int goodid, String path) {
        this.goodid = goodid;
        this.path = path;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagepath.goodId
     *
     * @mbg.generated
     */
    private Integer goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imagepath.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagepath.pathId
     *
     * @return the value of imagepath.pathId
     *
     * @mbg.generated
     */
    public Integer getPathid() {
        return pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagepath.pathId
     *
     * @param pathid the value for imagepath.pathId

     * @mbg.generated
     */
    public void setPathid(Integer pathid) {
        this.pathid = pathid;
    }

    /**
     * This method was generated by MyBatis Generato.
     * This method returns the value of the database column imagepath.goodId
     *
     * @return the value of imagepath.goodId
     *
     * @mbg.generated
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagepath.goodId
     *
     * @param goodid the value for imagepath.goodId
     *
     * @mbg.generated
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imagepath.path
     *
     * @return the value of imagepath.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imagepath.path
     *
     * @param path the value for imagepath.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ImagePath other = (ImagePath) that;
        return (this.getPathid() == null ? other.getPathid() == null : this.getPathid().equals(other.getPathid()))
                && (this.getGoodid() == null ? other.getGoodid() == null : this.getGoodid().equals(other.getGoodid()))
                && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imagepath
     *
     * @mbg.generated Wed Jul 24 09:45:07 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPathid() == null) ? 0 : getPathid().hashCode());
        result = prime * result + ((getGoodid() == null) ? 0 : getGoodid().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        return result;
    }
}